In [1]:
import numpy as np
import pandas as pd


In [2]:
np.set_printoptions(suppress = True, linewidth = 100 ,precision = 2)
 #this is to display the output completely and stopping scientific display

In [3]:
raw_data_np = np.genfromtxt('loan-data.csv', delimiter = ";", skip_header = 1, autostrip = True, encoding="ISO-8859-1")
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]],
      shape=(10000, 14))

In [4]:
np.isnan(raw_data_np).sum()

np.int64(88005)

In [5]:
temp_fill = np.nanmax(raw_data_np).round(2) + 1
temp_mean = np.nanmean(raw_data_np, axis = 0)
#axis = 0 means column wise for all rows

C:\Users\lavit\AppData\Local\Temp\ipykernel_17048\2174520810.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis = 0)


In [6]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temp_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                      temp_mean,
                      np.nanmax(raw_data_np, axis = 0)])

C:\Users\lavit\AppData\Local\Temp\ipykernel_17048\387489847.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis = 0),
C:\Users\lavit\AppData\Local\Temp\ipykernel_17048\387489847.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


In [8]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [9]:
#splitting data into numeric and string



In [10]:
column_strings = np.argwhere(np.isnan(temp_mean)).squeeze() #we added squeeze function to convert the array into 1-d.
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [11]:
column_numeric = np.argwhere(np.isnan(temp_mean)== False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13])

In [12]:
#reimporting the dataset

In [13]:
loan_data_str = np.genfromtxt("loan-data.csv",
                             delimiter = ";",
                             skip_header = 1,
                             autostrip= True, usecols = column_strings,
                             dtype = str,
                             encoding="ISO-8859-1")
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [14]:
loan_data_numeric = np.genfromtxt("loan-data.csv",
                             delimiter = ";",
                             skip_header = 1,
                             autostrip= True, usecols = column_numeric,
                             filling_values = temp_fill,
                             encoding="ISO-8859-1")
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

In [15]:
header_full = np.genfromtxt("loan-data.csv",
                             delimiter = ";",
                             skip_footer = raw_data_np.shape[0],#becoz when we imported raw data we skip the header meaning it will ignore all the rows except the header
                             autostrip= True,
                             dtype = str,
                             encoding="ISO-8859-1")
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [16]:
header_str, header_numeric = header_full[column_strings], header_full[column_numeric]

In [17]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [19]:
#now data setup is complete
#now preprocess will starts


In [20]:
#creating checkpoints
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [21]:
checkpoint_test = checkpoint("checkpoint-test", header_str, loan_data_str)

In [22]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [23]:
np.array_equal(checkpoint_test['data'], loan_data_str)

True

In [24]:
#manipulating the strings column of dataset

In [25]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [26]:
header_str[0] = 'issue_date'

In [27]:
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [28]:
np.unique(loan_data_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [29]:
loan_data_str[:,0]= np.char.chararray.strip(loan_data_str[:,0],'-15')

In [30]:
loan_data_str

array([['May', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [31]:
np.unique(loan_data_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [32]:
months = np.array(["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])

In [33]:
for i in range(13):
    loan_data_str[:,0] = np.where(loan_data_str[:,0] == months[i],
                                 str(i),
                                  loan_data_str[:,0])

In [34]:
loan_data_str[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], shape=(10000,), dtype='<U69')

In [35]:
np.unique(loan_data_str[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [36]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [37]:
np.unique(loan_data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [38]:
#applying 1 for good and 0 for bad

In [39]:
status_bad = ['','Charged Off','Default','Late(31-120 days)']

In [40]:
loan_data_str[:,1]= np.where(np.isin(loan_data_str[:,1],status_bad),0,1)

In [41]:
np.unique(loan_data_str[:,1])

array(['0', '1'], dtype='<U69')

In [42]:
#cahnging term

In [43]:
np.unique(loan_data_str[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [44]:
loan_data_str[:,2] = np.char.chararray.strip(loan_data_str[:,2]," months")

In [45]:
np.unique(loan_data_str[:,2])

array(['', '36', '60'], dtype='<U69')

In [46]:
header_str[2] = "term_months"

In [47]:
#we will substitue empty space with the 60 months because in credit rating modeling we assume the missing data as the worst possible outcome
#here the 60 is the longest possible out of given data
loan_data_str[:,2] = np.where(loan_data_str[:,2]== '',
                              str(60),
                              loan_data_str[:,2])

In [48]:
np.unique(loan_data_str[:,2])

array(['36', '60'], dtype='<U69')

In [49]:
np.unique(loan_data_str[:,2])

array(['36', '60'], dtype='<U69')

In [50]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [51]:
loan_data_str[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], shape=(10000,), dtype='<U69')

In [52]:
np.unique(loan_data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [53]:
np.unique(loan_data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [54]:
#filling subgrade missing values
for i in np.unique(loan_data_str[:,3]):
    loan_data_str[:,4] = np.where(((loan_data_str[:,4]=='') & (loan_data_str[:,3]== i)),
                                 (i + '5'),
                                 loan_data_str[:,4])
    

In [55]:
np.unique(loan_data_str[:,4], return_counts = True)

(array(['5', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [56]:
loan_data_str[:,4] = np.where(((loan_data_str[:,4]=='5') & (loan_data_str[:,3]== "")),
                                 ('H1'),
                                 loan_data_str[:,4])

In [57]:
np.unique(loan_data_str[:,4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

In [58]:
print(np.unique(loan_data_str[loan_data_str[:, 3] == '', 4],return_counts = True))

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F4', 'G1', 'G2',
       'G5', 'H1'], dtype='<U69'), array([ 8, 16, 19, 17, 25, 17, 27, 34, 35, 23, 34, 28, 32, 30, 33, 13,  9, 13, 17, 10, 17, 14,  7,
        8,  5,  5,  4,  2,  1,  2,  1,  9]))


In [59]:
#hence we have all the values in subgrade even if the value of grade is empty so we can delete the grade column as it is reduntant.
loan_data_str = np.delete(loan_data_str, 3, axis= 1)

In [60]:
loan_data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], shape=(10000,), dtype='<U69')

In [61]:
header_str = np.delete(header_str,3)

In [62]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [63]:
np.unique(loan_data_str[:,3]).shape[0]

36

In [64]:
keys = list(np.unique(loan_data_str[:,3]))
values = list(range(1,np.unique(loan_data_str[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys, values))

In [65]:
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36}

In [66]:
for i in np.unique(loan_data_str[:,3]):
    loan_data_str[:,3] = np.where(loan_data_str[:,3] == i,
                                 str(dict_sub_grade[i]),
                                 loan_data_str[:,3])

In [67]:
np.unique(loan_data_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [68]:
#now next column verification status
np.unique(loan_data_str[:,4], return_counts = True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([ 500, 2673, 4116, 2711]))

In [69]:
loan_data_str[:,4] = np.where((loan_data_str[:,4]== '') | (loan_data_str[:,4] == 'Not Verified'),
                             0,
                            1)

In [70]:
np.unique(loan_data_str[:,4], return_counts = True)

(array(['0', '1'], dtype='<U69'), array([3173, 6827]))

In [71]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [72]:
#url
loan_data_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'],
      shape=(10000,), dtype='<U69')

In [ ]:
np.char.chararray.strip(loan_data_str[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [74]:
loan_data_str[:,5] =  np.char.chararray.strip(loan_data_str[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")


In [75]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [76]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.], shape=(10000,))

In [77]:
loan_data_str[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [78]:
np.array_equal(loan_data_str[:,5].astype(dtype = "int32"), loan_data_numeric[:,0].astype(dtype = "int32"))

True

In [79]:
#as both loan id and url is based on same loan id we can remove the url column and its data from the dataset
loan_data_str =  np.delete(loan_data_str, 5 ,axis =1)
header_str = np.delete(header_str, 5)

In [80]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [81]:
states_names, states_count = np.unique(loan_data_str[:,5], return_counts = True)

In [82]:
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [83]:
loan_data_str[:,5] = np.where(loan_data_str[:,5]=='',
                              str(0),
                              loan_data_str[:,5])

In [84]:
states_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])


In [85]:
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_west),
                             str(1),
                             loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_south),
                             str(2),
                             loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_midwest),
                             str(3),
                             loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_east),
                             str(4),
                             loan_data_str[:,5])

In [86]:
np.unique(loan_data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

now we have all the strings converted into some form of numeric number in the strings
now we will cast them into integer and save the progress as checkpoint

In [87]:
loan_data_str

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], shape=(10000, 6), dtype='<U69')

In [88]:
loan_data_str = loan_data_str.astype(int)

In [89]:
loan_data_str

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6))

In [90]:
#checkpoint 1
checkpoint_str = checkpoint("checkpoint-strings", header_str, loan_data_str)

In [91]:
checkpoint_str['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6))

In [92]:
np.array_equal(checkpoint_str['data'],loan_data_str)

True

##manipulating_numeric_data

In [93]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

In [94]:
np.isnan(loan_data_numeric).sum()

np.int64(0)

In [95]:
#0 shows no missing value, but still when we load the data set we had substituted the missing value with temporay filler which needs to be substituted with worst possible values

In [96]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [97]:
temp_fill

np.float64(68616520.0)

In [98]:
np.isin(loan_data_numeric[:,0], temp_fill).sum() #zero means no value is equal to temporary value

np.int64(0)

In [99]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [100]:
#since only funded amt is only column where min value will be the worst possible and rest all must be substituted with max value of that column

In [101]:
temp_stats[:,column_numeric]


array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [102]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

In [103]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temp_fill,
                                 temp_stats[0,column_numeric[2]],
                                 loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

In [104]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [105]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temp_fill,
                                     temp_stats[2,column_numeric[i]],
                                     loan_data_numeric[:,i])

In [106]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]],
      shape=(10000, 6))

In [ ]:
eur_usd = np.genfromtxt('EUR-USD.csv', delimiter = ',', autostrip = True, skip_header = 1, usecols = 3) #we will use adjusted closing price for adjusting

In [108]:
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [109]:
loan_data_str[:,0]

array([ 5,  0,  9, ...,  6,  4, 12], shape=(10000,))

In [110]:
exchange_rate = loan_data_str[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                            eur_usd[i-1],
                            exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                        np.mean(eur_usd),
                        exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [111]:
exchange_rate.shape

(10000,)

In [112]:
loan_data_numeric.shape

(10000, 6)

In [113]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [114]:
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))

In [115]:
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [116]:
#now converting from usd to eur

In [117]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [118]:
col_dollar = np.array([1,2,4,5])

In [119]:
loan_data_numeric[:,col_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]], shape=(10000, 4))

In [120]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]],
      shape=(10000, 7))

In [121]:
#now adding all the converted amounts into the original dataset
for i in col_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6], (10000,1))))


In [122]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]],
      shape=(10000, 11))

In [123]:
header_additional = np.array([col_name + '_EUR' for col_name in header_numeric[col_dollar]])

In [124]:
header_numeric.shape

(7,)

In [125]:
header_numeric = np.concatenate((header_numeric,header_additional))

In [126]:
header_numeric.shape

(11,)

In [127]:
header_numeric[col_dollar] = np.array([col_name + '_USD' for col_name in header_numeric[col_dollar]])

In [128]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [129]:
#rearranging the header in order where usd and eur columns come side by side
col_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [130]:
header_numeric = header_numeric[col_index_order]

In [131]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [132]:
loan_data_numeric = loan_data_numeric[:,col_index_order]

In [133]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
      shape=(10000, 11))

In [134]:
header_numeric[5]

np.str_('int_rate')

In [135]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99], shape=(10000,))

In [136]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [137]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29], shape=(10000,))

In [138]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", header_numeric,loan_data_numeric)


In [139]:
checkpoint_numeric['header'],checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
       shape=(10000, 11)))

In [140]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
      shape=(10000, 11))

In [141]:
checkpoint_str['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6))

In [142]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_str['data']))

In [143]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]],
      shape=(10000, 17))

In [144]:
header_full = np.concatenate((checkpoint_numeric['header'],checkpoint_str['header']))

In [145]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [146]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [147]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [148]:
loan_data_preprocessed = np.vstack((header_full,loan_data))

In [149]:
np.savetxt("loan-data-preprocessed.csv",
          loan_data_preprocessed,
          fmt = "%s",
          delimiter = ",")